baseurl = "https://kotlin.how"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Enrico Casini"
title = "Kotlin.how"
disqusshortname = "icochico"
pluralizelisttitles = false
disqusShortname = "icochico"

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Nov 9, 2017"
dateformfull = "Thu Nov 9 2017 17:41:05 CST"
description = "Example blg"
copyright = "Copyright © 2017 Enrico Casini"
logofile = "images/logo.png"
faviconfile = "images/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "kotlinhow"
email = "kotlin.how@gmail.com"
linkedin = "enricocasini"
twitter = "ico_chico"
social_banner = "images/logo.png"
posts_navigation = true
small_banner_logo = false

