baseurl = "https://kotlin.how"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Enrico Casini"
title = "Cocoa Enhanced"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Nov 9, 2017"
dateformfull = "Thu Nov 9 2017 17:41:05 CST"
description = "Example blg"
copyright = "Copyright © 2017 Enrico Casini"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "example"
email = "kotlin.how@gmail.com"
linkedin = "john-example-aa80ue8è"
twitter = "example"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false

