baseURL = "https://kotlin-how.netlify.com"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Kotlin.How"
theme = "hugo-theme-learn"
themesdir = "themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
disqusShortname = "icochico"

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
  showVisitedLinks = true
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Extras"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/kotlinhow"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits"
url = "https://www.ihmc.us/groups/ecasini"
weight = 30

